### PR TITLE
Return date, not time from stats endpoint

### PR DESCRIPTION
**Pull request by i-oden**
## Before submitting this PR

1. **Description:** Atm the stats endpoint returns the date and time from the reporting row, but the time is always 00:00:00 -- only return date. At some point we could change the database to only save the date, but that's an unnecessary step atm. 
2. **Jira task / GitHub issue:** DDS-1575
3. **How to test:** _Add information on how someone could manually test this functionality. As detailed as possible._
4. **Type of change:** [_Check the relevant boxes in the section below_](#what-type-of-changes-does-the-pr-contain)
5. **Add docstrings and comments to code**, _even if_ you personally think it's obvious.

## What _type of change(s)_ does the PR contain?

- [x] New feature
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [x] Non-breaking
- [ ] Database change
  - [ ] Migration _included in PR_
  - [ ] Migration _not needed_
- [ ] Bug fix
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [ ] Non-breaking
- [ ] Security Alert fix
- [ ] Documentation
- [ ] Tests **(only)**
- [ ] Workflow

## Checklist

- [Sprintlog](../SPRINTLOG.md)
  - [x] Added
  - [ ] Not needed (E.g. PR contains _only_ tests)
- Rebase / Update / Merge _from_ base branch (the branch from which the current is forked)
  - [ ] Done
  - [ ] Not needed
- Blocking PRs
  - [ ] Merged
  - [x] No blocking PRs
- PR to `master` branch
  - [ ] Yes: Read [the release instructions](https://github.com/ScilifelabDataCentre/dds_web/blob/master/doc/procedures/new_release.md)
    - [ ] I have followed steps 1-8.
  - [x] No

## Actions / Scans

- **Black**: Python code formatter. Does not execute. Only tests.
  Run `black .` locally to execute formatting.
  - [x] Passed
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
  Run `npx prettier --write .` locally to execute formatting.
  - [x] Passed
- **Yamllint**: Linting of yaml files.
  - [x] Passed
- **Tests**: Pytest to verify that functionality works as expected.
  - [ ] New tests added
  - [ ] No new tests
  - [ ] Passed
- **CodeQL**: Scan for security vulnerabilities, bugs, errors
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Trivy**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Snyk**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1456"></a>

### CODE REVIEW

**Comment by i-oden** [comment]
Tests needed.

**Comment by valyo** [comment]
I added a check for the "columns" part of `response`, and since this and the date thing are the only changes, and the coverage of `superadmin_only` is already close to 99%, this should be enough. 
Or do you have some other tests in mind?

**Comment by i-oden** [comment]
> I added a check for the "columns" part of `response`, and since this and the date thing are the only changes, and the coverage of `superadmin_only` is already close to 99%, this should be enough. Or do you have some other tests in mind?

Yeah that's fine 👍🏻 
You can resolve conflicts and mark as ready for review and then I can look again

**Comment by i-oden** [comment]
Can you approve this PR @valyo ? I was going to but I can't because it's mine.

**Review by valyo — APPROVED** [review]

**Comment by i-oden** [comment]
Thank you 😄

**Pull request merged**
