### PR TITLE
WIP: Start bringing back the front-end

### PR DESCRIPTION
**Pull request by ewels**
Started restoring the front-end that we had previously.

Taking files from and referring to the `web_EOL` tag: https://github.com/ScilifelabDataCentre/dds_web/tree/web_EOL

Phil

### CODE REVIEW

**Comment by ewels** [comment]
Note: We are using bootstrap and [bootstrap-dark-5](https://www.npmjs.com/package/bootstrap-dark-5) at the moment in this PR. There is talk of bootstrap including a native dark mode in the near-ish future and as a result there is likely to be (a) major changes / end of support in bs-dark-5 and (b) the need to strip this out and refactor that code at some point in the future.

So for now, I've pinned the exact versions of both of those npm packages. When native bootstrap has dark mode, we can come back and update and remove the custom dark mode stuff if we want.

**Comment by alneberg** [comment]
I got this error when trying to run with docker-compose:

```
dds_nodebuilder  | npm ERR! code 1
dds_nodebuilder  | npm ERR! path /build/node_modules/node-sass
dds_nodebuilder  | npm ERR! command failed
dds_nodebuilder  | npm ERR! command sh -c node scripts/install.js
dds_nodebuilder  | npm ERR! internal/modules/cjs/loader.js:1131
dds_nodebuilder  | npm ERR!     throw err;
dds_nodebuilder  | npm ERR!     ^
dds_nodebuilder  | npm ERR!
dds_nodebuilder  | npm ERR! SyntaxError: /build/node_modules/har-schema/lib/request.json: Unexpected end of JSON input
dds_nodebuilder  | npm ERR!     at parse (<anonymous>)
dds_nodebuilder  | npm ERR!     at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
dds_nodebuilder  | npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
dds_nodebuilder  | npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
dds_nodebuilder  | npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
dds_nodebuilder  | npm ERR!     at require (internal/modules/cjs/helpers.js:101:18)
dds_nodebuilder  | npm ERR!     at Object.<anonymous> (/build/node_modules/har-schema/lib/index.js:19:12)
dds_nodebuilder  | npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
dds_nodebuilder  | npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
dds_nodebuilder  | npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
dds_nodebuilder  |
dds_nodebuilder  | npm ERR! A complete log of this run can be found in:
dds_nodebuilder  | npm ERR!     /root/.npm/_logs/2022-03-04T06_19_50_046Z-debug-0.log
```

Not sure if its anything on my side, if I should perhaps clean up something from before?

**Comment by ewels** [comment]
Yeah I would maybe try deleting and recloning. Or at least deleting the `static` directory and checking it out again. Lots of untracked files in there.

**Comment by ewels** [comment]
Right, tests finally passing I think! 🎉 

Still a couple of things left to do, but should nearly be there now:

- Merge some of the template files, eg. `login.html` with the old `login_form.html` component
- Actually do a full manual run through of functionality to make sure that I haven't broken stuff.

Then some additional stuff, but this is probably best done in a separate PR:

- Update the newer template files to use consistent styling
- Fix and tidy the HTML template whitespace formatting

**Comment by inaod568** [comment]
@ewels Could you add the link to the change password page before I approve and merge?

**Comment by ewels** [comment]
> @ewels Could you add the link to the change password page before I approve and merge?

Done ✨  (link is within a new account / profile page, get there by clicking your username in the nav)

**Review by inaod568 — APPROVED** [review]
Works like a charm and looks awesome! 👏🏻 

Not sure I understand the use of `flask.g.current_user` in addition to the others but I'm fine with merging to `dev` since it works.

**Pull request merged**
