### PR TITLE
New endpoint for checking if any projects are busy

### PR DESCRIPTION
**Pull request by inaod568**
> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

# Description

New endpoint for checking if any projects are busy so that we (super admins) can avoid maintenance while upload / download etc is ongoing. 

- [x] Add a summary of the changes and the related issue
- [x] Add motivation and context regarding why the change is needed
- [x] Fixes DDS-1346

## Type of change

- [x] New feature (non-breaking)

# Checklist:

## General

- [x] [Changelog](../CHANGELOG.md): New row added
- [x] Code change
  - [x] Self-review of code done
  - [x] Comments added, particularly in hard-to-understand areas

## Repository / Releases

- [x] Blocking PRs have been merged
- [x] Rebase / update of branch done
- [x] Product Owner / Scrum Master

## Checks

- [x] Formatting: Black & Prettier checks pass
- [x] CodeQL passes
- [x] Tests
  - [x] I have added tests for the new code
  - [x] The tests pass
- [x] Trivy / Snyk:
  - [x] There are no new security alerts

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1288"></a>

### CODE REVIEW

**Review by valyo — COMMENTED** [review]
Looks fine, but approval can come when it works as expected with a new CLI command `dds project status busy --list`

**Comment by inaod568** [comment]
> Looks fine, but approval can come when it works as expected with a new CLI command `dds project status busy --list`

@valyo I think we can approve and merge the web PR and make a new release of the CLI as well. I would prefer not changing the deployment time to Wednesday since people may have planned for it tomorrow etc. That way we only need to do a new minor CLI release when the command is done and the rest will still work.

**Comment by valyo** [comment]
> @valyo I think we can approve and merge this PR and make a new release of the CLI as well. I would prefer not changing the deployment time to Wednesday since people may have planned for it tomorrow etc. That way we only need to do a new minor CLI release when the command is done and the rest will still work.

ok, I am approving it then

**Review by valyo — APPROVED** [review]

**Comment by inaod568** [comment]
@valyo Great, thanks!

**Pull request merged**
