### PR TITLE
Cleanout web WIP/Suggestion

### PR DESCRIPTION
**Pull request by alneberg**
I probably went overboard with deleting the web related code. A lot of the python code will probably be reused in the api quite soon, but it's easy to fetch from the git history.

I'm mostly making this PR to see what you think, should we be more careful with deleting or should we bring things back one by one when we need them?

### CODE REVIEW

**Review by MatthiasZepper — APPROVED** [review]
Funny. I was suggesting exactly the same to Volkan this morning during the meeting...

**Comment by inaod568** [comment]
Do we have a dedicated branch or tag for remembering the version before the deletion?

**Comment by alneberg** [comment]
Yes I created the https://github.com/ScilifelabDataCentre/dds_web/tree/web_EOL branch. But maybe a tag is easier to find, maybe both?

**Comment by inaod568** [comment]
Ah okey great. Yes I think both can be good 👍🏻

**Review by inaod568 — APPROVED** [review]

**Comment by inaod568** [comment]
Will merge this now, @alneberg can you fix the tag?

**Pull request merged**
