### PR TITLE
Remove oauth

### PR DESCRIPTION
**Pull request by talavis**
> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

# Description

Remove `authlib` and it's setup and config as it's currently not used for anything.

- [X] Add a summary of the changes and the related issue
- [ ] Add motivation and context regarding why the change is needed
- [ ] List / describe any dependencies or other changes required for this change
- [ ] Fixes [link to issue / Jira issue ID]

## Type of change

- [ ] Documentation
- [ ] Workflow
- [ ] Security Alert fix
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (breaking, will cause existing functionality to not work as expected)
- [ ] Tests (only)
- [X] Refactor

# Checklist:

## General

- [ ] [Changelog](../CHANGELOG.md): New row added. Not needed when PR includes _only_ tests.
- [ ] Database schema has changed
  - [ ] A new migration is included in the PR
  - [ ] The change does not require a migration
- [ ] Code change
  - [X] Self-review of code done
  - [ ] Comments added, particularly in hard-to-understand areas
  - [ ] Documentation is updated

## Repository / Releases

- [X] Blocking PRs have been merged
- [X] Rebase / update of branch done
- [ ] PR to `master` branch (Product Owner / Scrum Master)
  - [ ] The [version](../dds_web/version.py) is updated
    - [ ] I am bumping the major version (e.g. 1.x.x to 2.x.x)
      - [ ] I have made the corresponding changes to the CLI version
  - Backward compatible
    - [X] Yes: The code works together with `dds_cli/master` branch
    - [ ] No: The code **does not** entirely / at all work together with the `dds_cli/master` branch. _Please add detailed and clear information about the broken features_

## Checks

- [X] Formatting: Black & Prettier checks pass
- [X] CodeQL passes
- [ ] Tests
  - [ ] I have added tests for the new code
  - [ ] The tests pass
- [X] Trivy / Snyk:
  - [X] There are no new security alerts
  - [ ] This PR fixes new security alerts
  - [ ] Security alerts have been dismissed
  - [ ] PR will be merged with new security alerts; This is why: _Please add a short description here_

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1332"></a>

### CODE REVIEW

**Review by inaod568 — CHANGES_REQUESTED** [review]
Verkar som att `cryptography` behöver `authlib` - får detta när jag startar upp
```bash
dds_backend      | AttributeError: module 'cryptography.hazmat.primitives.ciphers' has no attribute 'aead'
```

**Comment by talavis** [comment]
Wtf? Authlib lists Cryptography as a dependency... I will look into it.

Actually, it sounds more like a spelling error. Are you sure you have no other changes in your code?

**Comment by inaod568** [comment]
> Wtf? Authlib lists Cryptography as a dependency... I will look into it.
> 
> Actually, it sounds more like a spelling error. Are you sure you have no other changes in your code?

This was just testing your PR, no other changes. And the code is frequently used, and no changes there since the last release

**Comment by inaod568** [comment]
It's complaining about `aead` but it definitely exists.
https://cryptography.io/en/latest/hazmat/primitives/aead/#

**Comment by i-oden** [comment]
Has been open for a while. Not sure of solution. Closing for now.

**Pull request closed without merging**
