### PR TITLE
Use basic authentication only for the token endpoint and token authentication for the rest

### PR DESCRIPTION
**Pull request by aanil**
The `flask.current_app.config.get("TOKEN_ENDPOINT_ACCESS_LIMIT")` in the limiter decorator gives me the following error when running tests. It seems to perform ok otherwise. Anyone know how to pass the application context to the test?

> 
> dds_backend | ImportError while loading conftest '/code/tests/conftest.py'.
> dds_backend | tests/__init__.py:4: in <module>
> dds_backend |     import dds_web.api.errors as ddserr
> dds_backend | dds_web/api/__init__.py:13: in <module>
> dds_backend |     from dds_web.api import user
> dds_backend | dds_web/api/user.py:357: in <module>
> dds_backend |     class Token(flask_restful.Resource):
> dds_backend | dds_web/api/user.py:362: in Token
> dds_backend |     flask.current_app.config.get("TOKEN_ENDPOINT_ACCESS_LIMIT"),
> dds_backend | /usr/local/lib/python3.10/site-packages/werkzeug/local.py:432: in __get__
> dds_backend |     obj = instance._get_current_object()
> dds_backend | /usr/local/lib/python3.10/site-packages/werkzeug/local.py:554: in _get_current_object
> dds_backend |     return self.__local()  # type: ignore
> dds_backend | /usr/local/lib/python3.10/site-packages/flask/globals.py:52: in _find_app
> dds_backend |     raise RuntimeError(_app_ctx_err_msg)
> dds_backend | E   RuntimeError: Working outside of application context.
> dds_backend | E
> dds_backend | E  This typically means that you attempted to use functionality that needed 
> dds_backend | E   to interface with the current application object in some way. To solve
> dds_backend | E   this, set up an application context with app.app_context().  See the
> dds_backend | E   documentation for more information.

### CODE REVIEW

**Comment by inaod568** [comment]
> The `flask.current_app.config.get("TOKEN_ENDPOINT_ACCESS_LIMIT")` in the limiter decorator gives me the following error when running tests. It seems to perform ok otherwise. Anyone know how to pass the application context to the test?
> 
> > dds_backend | ImportError while loading conftest '/code/tests/conftest.py'.
> > dds_backend | tests/**init**.py:4: in 
> > dds_backend |     import dds_web.api.errors as ddserr
> > dds_backend | dds_web/api/**init**.py:13: in 
> > dds_backend |     from dds_web.api import user
> > dds_backend | dds_web/api/user.py:357: in 
> > dds_backend |     class Token(flask_restful.Resource):
> > dds_backend | dds_web/api/user.py:362: in Token
> > dds_backend |     flask.current_app.config.get("TOKEN_ENDPOINT_ACCESS_LIMIT"),
> > dds_backend | /usr/local/lib/python3.10/site-packages/werkzeug/local.py:432: in **get**
> > dds_backend |     obj = instance._get_current_object()
> > dds_backend | /usr/local/lib/python3.10/site-packages/werkzeug/local.py:554: in _get_current_object
> > dds_backend |     return self.__local()  # type: ignore
> > dds_backend | /usr/local/lib/python3.10/site-packages/flask/globals.py:52: in _find_app
> > dds_backend |     raise RuntimeError(_app_ctx_err_msg)
> > dds_backend | E   RuntimeError: Working outside of application context.
> > dds_backend | E
> > dds_backend | E  This typically means that you attempted to use functionality that needed
> > dds_backend | E   to interface with the current application object in some way. To solve
> > dds_backend | E   this, set up an application context with app.app_context().  See the
> > dds_backend | E   documentation for more information.

I'm assuming that it has something to do with having to access the variable in the `with app.app_context` section: https://github.com/aanil/dds_web/blob/3e3768d144a9a67bae6b66a98d763da067d279c5/dds_web/__init__.py#L166-L188 
We've had similar errors and then that has been the issue

**Comment by worukan** [comment]
I think you can observe from some of the written tests that client is passed as a parameter to the test function. I think that provides the app context.

**Comment by aanil** [comment]
I've changed how the limit is passed to the limiter decorator, and the tests pass now.

**Comment by worukan** [comment]
I think code changes looks ok, but I'm not sure if I understand it clearly.

**What I understand mixed with what I don't understand:**
It is allowed up to 10 authentication requests per hour. There is an error saying too many request in one day. Yet I haven't seen any conversion between day and hours?
Also I don't see the reason for **basic auth only for token endpoint and token auth for the rest**?? I understood as you had a problem before and we needed this change to make it work. However your decorator seems to be placed on both authentication mechanisms. Could you please clarify?

**Comment by aanil** [comment]
> I think code changes looks ok, but I'm not sure if I understand it clearly.
> 
> **What I understand mixed with what I don't understand:** It is allowed up to 10 authentication requests per hour. There is an error saying too many request in one day. Yet I haven't seen any conversion between day and hours? Also I don't see the reason for **basic auth only for token endpoint and token auth for the rest**?? I understood as you had a problem before and we needed this change to make it work. However your decorator seems to be placed on both authentication mechanisms. Could you please clarify?

I've changed the error message, I missed changing it when we decided to make it per hour. I'm not sure I understand your second question? The decorator is used only on the classes `Token` and `EncryptedToken` which provide a token when requested. Johannes said we might only use the `EncryptedToken` in the future and phase out `Token`, so I added it to both.

**Comment by worukan** [comment]
You are right! I am fooled by the way GitHub shows the changes. Both has basic authentication. Good!
Thanks for the clarification!

**Review by worukan — APPROVED** [review]

**Review by inaod568 — APPROVED** [review]
LGTM! 👏🏻

**Review by alneberg — APPROVED** [review]
All good from what I can tell!

**Pull request merged**
