### PR TITLE
Bump actions/checkout to v4

### PR DESCRIPTION
**Pull request by valyo**
## Read this before submitting the PR

1. Always create a Draft PR first
2. Go through sections 1-5 below, fill them in and check all the boxes
3. Make sure that the branch is updated; if there's an "Update branch" button at the bottom of the PR, rebase or update branch.
4. When all boxes are checked, information is filled in, and the branch is updated: mark as Ready For Review and tag reviewers (top right)
5. Once there is a submitted review, implement the suggestions (if reasonable, otherwise discuss) and request an new review.

If there is a field which you are unsure about, enter the edit mode of this description or go to the [PR template](../.github/pull_request_template.md); There are invisible comments providing descriptions which may be of help.

## 1. Description / Summary

Bump checkout action to v4, after noticing warning:
`The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/`

## 2. Jira task / GitHub issue

_Link to the github issue or add the Jira task ID here._

## 3. Type of change

What _type of change(s)_ does the PR contain?

**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**

- [ ] New feature
  - [ ] Breaking: _Why / How? Add info here._ 
  - [ ] Non-breaking 
- [ ] Database change: _Remember the to include a new migration version, **or** explain here why it's not needed._ 
- [ ] Bug fix 
- [ ] Security Alert fix 
  - [ ] Package update 
    - [ ] Major version update 
- [ ] Documentation 
- [x] Workflow 
- [ ] Tests **only** 

## 4. Additional information

- [x] [Sprintlog](../SPRINTLOG.md) 
- [ ] Blocking PRs 
  - [ ] Merged 
- [ ] PR to `master` branch: \_If checked, read [the release instructions](../doc/procedures/new_release.md) 
  - [ ] I have followed steps 1-8. 

## 5. Actions / Scans

_Check the boxes when the specified checks have passed._

**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](../.github/pull_request_template.md).**

- [x] **Black**

- [x] **Prettier**

- [x] **Yamllint**

- [x] **Tests**

- [x] **CodeQL**

- [x] **Trivy**

- [x] **Snyk**

### CODE REVIEW

**Review by i-oden — CHANGES_REQUESTED** [review]
Sprintlog and check the scan boxes

**Review by i-oden — CHANGES_REQUESTED** [review]
Just wondering if we shouldn't update all instances of `actions/checkout@v4` and not only this workflow file? 

Also, I updated the branch and resolved the sprintlog, and now checks are failing again, not sure why?

**Comment by i-oden** [comment]
> > Just wondering if we shouldn't update all instances of `actions/checkout@v4` and not only this workflow file?
> > Also, I updated the branch and resolved the sprintlog, and now checks are failing again, not sure why?
> 
> Again the too many requests, if you run it locally with the vpn it also hits it. Yesterday it also happened a lot with the PRs. They must have decreased the limits recently or there is something that changed, because it is too much of a coincidence now
> 
> I read somewhere a solution to cache images to avoid pulling them in the Actions everytime, only solution for now is to re-run the jobs after a time
> 
> image

🙃

**Comment by i-oden** [comment]
> For some reason I cannot "Approve" or "Request changes" here, only "Comment". It looks good, maybe as Ina suggested we should bump this action in all our workflows.

@valyo You can't approve because you created the PR 😄 So you're the one making potential changes to the other actions as well

**Comment by valyo** [comment]
> > For some reason I cannot "Approve" or "Request changes" here, only "Comment". It looks good, maybe as Ina suggested we should bump this action in all our workflows.
> 
> @valyo You can't approve because you created the PR 😄 So you're the one making potential changes to the other actions as well

🙃

**Comment by valyo** [comment]
ok, if we have agreed that all actions should be bumped, I'll add the changes in this PR

**Comment by i-oden** [comment]
> ok, if we have agreed that all actions should be bumped, I'll add the changes in this PR

Yes go ahead and do that

**Comment by i-oden** [comment]
@valyo This was a mistake on my end. I was suppose to push to my PR. I'll fix this PR instead.

**Review by i-oden — APPROVED** [review]

**Pull request merged**
