### PR TITLE
Run trivy when PR created and on schedule

### PR DESCRIPTION
**Pull request by inaod568**
# Description

1. Added trivy to publishing workflow
2. Changed name of workflow 
3. Changed occurrence of trivy cronjob
4. Fixed issues reported 

- [x] Summary of the changes and the related issue
- [x] Relevant motivation and context

## Type of change

- [x] Workflow 

# Checklist:

Please delete options that are not relevant.

- [x] Any dependent changes have been merged and published in downstream modules
- [x] Rebase/merge the branch which this PR is made to

## Formatting and documentation

- [x] I have added a row in the [changelog](../CHANGELOG.md)
- [x] The code follows the style guidelines of this project: Black / Prettier formatting
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Tests

- [x] New and existing unit tests pass locally with my changes

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1276"></a>

### CODE REVIEW

**Comment by valyo** [comment]
trivy.yml is still here, wasn't it scanning the wrong image when run separately? Ok otherwise.

**Review by valyo — APPROVED** [review]

**Comment by talavis** [comment]
> trivy.yml is still here, wasn't it scanning the wrong image when run separately? Ok otherwise.

It is supposed to look at `:latest` to make sure that your currently deployed image does not have any security issues. It was temporarily changed to `:dev` so you can get rid of ~1000 security issues that makes it impossible to see the important ones.

**Review by talavis — APPROVED** [review]

**Comment by valyo** [comment]
> It is supposed to look at `:latest` to make sure that your currently deployed image does not have any security issues. It was temporarily changed to `:dev` so you can get rid of ~1000 security issues that makes it impossible to see the important ones.

ok, so the trivy.yml as a cron job is supposed to check the `:dev` image every day, and the Trivy part in `publish_and_trivyscan.yml`should check each new image build on a push, is this correct?

**Comment by talavis** [comment]
> > It is supposed to look at `:latest` to make sure that your currently deployed image does not have any security issues. It was temporarily changed to `:dev` so you can get rid of ~1000 security issues that makes it impossible to see the important ones.
> 
> ok, so the trivy.yml as a cron job is supposed to check the `:dev` image every day, and the Trivy part in `publish_and_trivyscan.yml`should check each new image build on a push, is this correct?

It should be changed back to `:latest` once you have made a release based on the alpine base image. Otherwise correct.

**Pull request merged**
