### PR TITLE
Scan code with Snyk

### PR DESCRIPTION
**Pull request by i-oden**
> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

# Description

- [x] Summary of the changes and the related issue: Include snyk scanning since other actions miss certain things.
- Fixes an issue in GitHub / Jira:
  - [x] Yes: DDS-1442

## Type of change

- [x] Workflow

# Checklist:

## General

- [x] [Changelog](../CHANGELOG.md): New row added. Not needed when PR includes _only_ tests.

## Repository / Releases

- [x] Rebase / update of branch done

## Checks

- [x] CodeQL passes
- [x] Snyk scan passes
- [x] Formatting: Black & Prettier checks pass
- Tests
  - [x] The tests pass
- Trivy:
  - [x] There are no new security alerts

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1349"></a>

### CODE REVIEW

**Review by valyo — APPROVED** [review]
Looks good.
What about those warnings about user.py? I guess the ones about hardcoded creds can be easily dismissed, but I am not sure about the `Open Redirect` ones

**Comment by i-oden** [comment]
> Looks good. What about those warnings about user.py? I guess the ones about hardcoded creds can be easily dismissed, but I am not sure about the `Open Redirect` ones

Aha, I didn't see these, I'll have a look during the day and see what to do.

**Comment by i-oden** [comment]
The issues are something that I've actually looked at previously. I'll look at it again.

**Comment by i-oden** [comment]
@valyo It was indeed a warning that CodeQL had already previously warned about. It complains about the redirects but we're already using a utils function to check that the redirect is safe. Plus we may rewrite this code when doing the web again. So I've dismissed those. 
There where also warnings about the credentials as you mentioned, but all of them are for the tests, so I have dismissed them with the reason "used in tests" -- not used in production.

**Pull request merged**
