### PR TITLE
AddUser: Specific error message for unit users

### PR DESCRIPTION
**Pull request by MatthiasZepper**
Distinct error message if the user to be added to a project is a unit user. 

- [ ] Tests passing
- [x] Black formatting
- [ ] Migrations for any changes to the database schema
- [x] Rebase/merge the `dev` branch
- [x] Note in the CHANGELOG

### CODE REVIEW

**Comment by inaod568** [comment]
@MatthiasZepper which card is this connected to?

**Comment by MatthiasZepper** [comment]
> @MatthiasZepper which card is this connected to?

None. This afternoon, we both - Sofia and me - were puzzled when she couldn't invite me to the system because I still had a lingering, yet expired, invite for a unit user and the error message rather indicated a typo in the specified user role.  It was quicker to fix right away than to generate a card for it first...

**Comment by inaod568** [comment]
> > @MatthiasZepper which card is this connected to?
> 
> None. This afternoon, we both - Sofia and me - were puzzled when she couldn't invite me to the system because I still had a lingering, yet expired, invite for a unit user and the error message rather indicated a typo in the specified user role. It was quicker to fix right away than to generate a card for it first...

@MatthiasZepper Then Phil has already created a PR for this https://github.com/ScilifelabDataCentre/dds_web/pull/1036

**Review by inaod568 — APPROVED** [review]
Works well 👍🏻

**Pull request merged**
