### PR TITLE
packages updated

### PR DESCRIPTION
**Pull request by rv0lt**
## Read this before submitting the PR

1. Always create a Draft PR first
2. Go through sections 1-5 below, fill them in and check all the boxes
3. Make sure that the branch is updated; if there's an "Update branch" button at the bottom of the PR, rebase or update branch.
4. When all boxes are checked, information is filled in, and the branch is updated: mark as Ready For Review and tag reviewers (top right)
5. Once there is a submitted review, implement the suggestions (if reasonable, otherwise discuss) and request an new review.

If there is a field which you are unsure about, enter the edit mode of this description or go to the [PR template](../.github/pull_request_template.md); There are invisible comments providing descriptions which may be of help.

## 1. Description / Summary

Updating vulnerable node packages 

---

The vulnerabilities identified by Trivy are:

- minimatch: 3.04 → 3.0.5
- request: 2.88.2 → _No fixed version_ 
- semver: 7.0.0 → 7.5.2
- tough-cookie: 2.5.0 → 4.1.3

To solve the dependencies, running 

`npm audit --fix`

Gives the packages that are needed to update to solve the vulnerabilities:

- minimatch is fixed by updating serve 
   - 13.0.4 → 14.2.1
- semver is fixed by updating nodemon
  - 2.0.22 → 3.0.1 
- tough cookie is fixed by updating node-sass
  - 7.0.3 → 9.0.0 

Perfrom update: 

`npm install node-sass@9.0.0 nodemon@3.0.1 serve@14.2.1 --save-dev`

Check for breaking changes:

 1. Re-build the image and execute the suite of tests to check no breaking tests.

2. Read the changelogs
  - Serve 
    - [Release notes](https://github.com/vercel/serve/releases)
    - The breaking change is rewritting the module in TypeScript, serve is used to serve the web. **Test manually web functions**
  - nodemon
    - [Release notes](https://github.com/remy/nodemon/releases) 
    - The breaking change is dropping support for node 8 (we use 18 currently)
  - node-sass
    - [Release notes](https://github.com/sass/node-sass/releases) 
    - Breaking changes are dropping support for node 17 or previous.

3. Run Trivy scanner again to check that node vuln are fixed

## 2. Jira task / GitHub issue

https://scilifelab.atlassian.net/jira/software/projects/DDS/boards/13?selectedIssue=DDS-1837

## 3. Type of change

What _type of change(s)_ does the PR contain?

**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**

- [ ] New feature
  - [ ] Breaking: _Why / How? Add info here._ 
  - [ ] Non-breaking 
- [ ] Database change: _Remember the to include a new migration version, **or** explain here why it's not needed._ 
- [ ] Bug fix 
- [x] Security Alert fix 
  - [x] Package update 
    - [x] Major version update 
- [ ] Documentation 
- [ ] Workflow 
- [ ] Tests **only** 

## 4. Additional information

- [x] [Sprintlog](../SPRINTLOG.md) 
- [ ] Blocking PRs 
  - [ ] Merged 
- [ ] PR to `master` branch: \_If checked, read [the release instructions](../doc/procedures/new_release.md) 
  - [ ] I have followed steps 1-8. 

## 5. Actions / Scans

_Check the boxes when the specified checks have passed._

**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](../.github/pull_request_template.md).**

- [x] **Black**

- [x] **Prettier**

- [x] **Yamllint**

- [x] **Tests**

- [x] **CodeQL**

- [x] **Trivy**

- [x] **Snyk**

### CODE REVIEW

**Comment by i-oden** [comment]
I'm a little confused. Why can't we update the packages that are pop up in the vulnerabilities? 
    minimatch: 3.04 → 3.0.5
    semver: 7.0.0 → 7.5.2
    tough-cookie: 2.5.0 → 4.1.3

These package versions aren't changed, only the ones that they depend on? Feels like it should be both in that case? Updating minimatch etc and also serve etc?

**Comment by rv0lt** [comment]
> I'm a little confused. Why can't we update the packages that are pop up in the vulnerabilities? minimatch: 3.04 → 3.0.5 semver: 7.0.0 → 7.5.2 tough-cookie: 2.5.0 → 4.1.3
> 
> These package versions aren't changed, only the ones that they depend on? Feels like it should be both in that case? Updating minimatch etc and also serve etc?


Because we don't use them directly. They are, instead, used by the other libraries we need.

Packages.json defines the libraries we need for the application to work. Node automatically updates packages-dev which the dependencies for that libraries.

Is the same issue with the pyhton packages and the dependency tree, but in this case node automatically resolves the conflict and tells you what you need to update.
https://umarfarooquekhan.medium.com/difference-between-package-json-and-package-lock-json-6225f83f247c

Example of the output of audit for minimatch
image

**Comment by i-oden** [comment]
> > I'm a little confused. Why can't we update the packages that are pop up in the vulnerabilities? minimatch: 3.04 → 3.0.5 semver: 7.0.0 → 7.5.2 tough-cookie: 2.5.0 → 4.1.3
> > These package versions aren't changed, only the ones that they depend on? Feels like it should be both in that case? Updating minimatch etc and also serve etc?
> 
> Because we don't use them directly. They are, instead, used by the other libraries we need.
> 
> Packages.json defines the libraries we need for the application to work. Node automatically updates packages-dev which the dependencies for that libraries.
> 
> Is the same issue with the pyhton packages and the dependency tree, but in this case node automatically resolves the conflict and tells you what you need to update. https://umarfarooquekhan.medium.com/difference-between-package-json-and-package-lock-json-6225f83f247c
> 
> Example of the output of audit for minimatch image

Ah ok!

**Review by i-oden — APPROVED** [review]
I've tested manually and from what I can tell there should be no issues.

**Pull request merged**
