### PR TITLE
Add troubleshooting to web

### PR DESCRIPTION
**Pull request by inaod568**
# Description

Troubleshooting document collected from Confluence page and displayed. The layout etc should of course be changed and when we work on the web more we can improve on it, but this is a good start and lets us have all information on confluence and just get it to the web page when needed. 

The same thing should be done with the technical overview. 

**To test that the cache works, manually:** 
1. Start `docker` with `full-dev` mode
2. Change the cache `ttl` from `hours=4` to `seconds=30` 
3. Go to dds home page and then click the Troubleshooting button in the navbar
4. Go to Confluence and change something at the top of that page (+ publish)
5. Go to the troubleshooting page again and update
6. Repeat 5 a couple of times
7. (Please change the confluence page back to what it was before the change)

This should mean that the troubleshooting guide should display the exact same thing for 30 seconds, and after that (when you update the page), the recent change should be visible. 

- [x] Summary of the changes and the related issue
- [x] Relevant motivation and context
- [ ] Any dependencies that are required for this change

Fixes DDS-1321

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

Please delete options that are not relevant.

- [x] Any dependent changes have been merged and published in downstream modules
- [x] Rebase/merge the branch which this PR is made to
- [x] Changes to the database schema: A new migration is included in the PR
- [ ] Product Owner / Scrum Master: This PR is made to the `master` branch and I have updated the [version](../dds_web/version.py)
- [ ] I am bumping the major version (e.g. 1.x.x to 2.x.x) and I have made the corresponding changes to the CLI version

## Formatting and documentation

- [x] I have added a row in the [changelog](../CHANGELOG.md)
- [x] The code follows the style guidelines of this project: Black / Prettier formatting
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Tests

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1244"></a>

### CODE REVIEW

**Comment by inaod568** [comment]
@valyo Replaced the flask-caching package, it's fine to test now (I've added a step by step in the description above).

**Comment by valyo** [comment]
Seems to work fine
the link the documentation as PDF doesn't work, but that should be fixed in confluence

**Comment by valyo** [comment]
wait, I didn't test properly

**Review by valyo — APPROVED** [review]
Tested the cacheing according to the steps and it works fine

**Comment by inaod568** [comment]
> and I fixed the link in confluence

Great! 
Adding tests before I merge. 

What was wrong with the link btw?

**Comment by valyo** [comment]
> What was wrong with the link btw?

I was lacking one "download" in the path

**Comment by inaod568** [comment]
> > What was wrong with the link btw?
> 
> I was lacking one "download" in the path

Aha!

**Pull request merged**
