### PR TITLE
Dds 1607 add test for deleted user when listing projects

### PR DESCRIPTION
**Pull request by rv0lt**
## Before submitting this PR

1. **Description:** Added a test to check for listing projects created by a deleted user
3. **Jira task / GitHub issue: DDS-1607
4. **How to test:** Execute the tests (?)
5. **Type of change:** [_Check the relevant boxes in the section below_](#what-type-of-changes-does-the-pr-contain)
6. **Add docstrings and comments to code**, _even if_ you personally think it's obvious.

## What _type of change(s)_ does the PR contain?

- [ ] New feature
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [ ] Non-breaking
- [ ] Database change
  - [ ] Migration _included in PR_
  - [ ] Migration _not needed_
- [ ] Bug fix
  - [ ] Breaking: _Please describe the reason for the break and how we can fix it._
  - [ ] Non-breaking
- [ ] Security Alert fix
- [ ] Documentation
- [x] Tests **(only)**
- [ ] Workflow

## Checklist

- [Sprintlog](../SPRINTLOG.md)
  - [ ] Added
  - [x] Not needed (E.g. PR contains _only_ tests)
- Rebase / Update / Merge _from_ base branch (the branch from which the current is forked)
  - [x] Done
  - [ ] Not needed
- Blocking PRs
  - [ ] Merged
  - [x] No blocking PRs
- PR to `master` branch
  - [ ] Yes: Read [the release instructions](https://github.com/ScilifelabDataCentre/dds_web/blob/master/doc/procedures/new_release.md)
    - [ ] I have followed steps 1-8.
  - [x] No

## Actions / Scans

- **Black**: Python code formatter. Does not execute. Only tests.
  Run `black .` locally to execute formatting.
  - [x] Passed
- **Prettier**: General code formatter. Our use case: MD and yaml mainly.
  Run `npx prettier --write .` locally to execute formatting.
  - [x] Passed
- **Yamllint**: Linting of yaml files.
  - [x] Passed
- **Tests**: Pytest to verify that functionality works as expected.
  - [ ] New tests added
  - [ ] No new tests
  - [x] Passed
- **CodeQL**: Scan for security vulnerabilities, bugs, errors
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Trivy**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed
- **Snyk**: Security scanner
  - [ ] New alerts: _Go through them and either fix, dismiss och ignore. Add reasoning in items below._
  - [ ] Alerts fixed: _What?_
  - [ ] Alerts ignored / dismissed: _Why?_
  - [x] Passed

<a href="https://gitpod.io/#https://github.com/ScilifelabDataCentre/dds_web/pull/1463"></a>

### CODE REVIEW

**Comment by rv0lt** [comment]
@i-oden

**Comment by i-oden** [comment]
@rv0lt This error message that pytest is raising is very confusing. It has nothing to do with that the endpoint doesn't exist, it's that you need to add the `boto3_session` as an argument in the test. Check the `test_create_project_with_credentials` in `test_project_creation.py` (or any other endpoint where the project creation is successful.

**Comment by rv0lt** [comment]
> @rv0lt This error message that pytest is raising is very confusing. It has nothing to do with that the endpoint doesn't exist, it's that you need to add the `boto3_session` as an argument in the test. Check the `test_create_project_with_credentials` in `test_project_creation.py` (or any other endpoint where the project creation is successful)

Ok, I was starting to suspect this error could be in that direction. Hopefully it works now!!

**Review by i-oden — CHANGES_REQUESTED** [review]
Looks good and it's easy to follow! Good job!

One suggestion I have is that we avoid hardcoding as much as possible, so for example we could 
1. define the username of the user that you want to delete
2. get the email for the user with that username (in case the email changes some time in the future) 
3. get a list of `public_id`s for the projects that the user has created 
4. then delete the user, log in and list all projects, exactly like you've already done
5. in the for loop on line 68, check if the `p_id` is in the list of `public_id`s you got from step 3

This way we cater for that the user may not exist, that the email may change and that we may add more projects with the creator `unituser2` in the future. So then we get good error messages and also we don't need to alter the tests if we change the user email or add more projects with the creator `unituser2`. 

Let me know if you want more details etc.

**Comment by rv0lt** [comment]
> Looks good and it's easy to follow! Good job!
> 
> One suggestion I have is that we avoid hardcoding as much as possible, so for example we could
> 
>     1. define the username of the user that you want to delete
> 
>     2. get the email for the user with that username (in case the email changes some time in the future)
> 
>     3. get a list of `public_id`s for the projects that the user has created
> 
>     4. then delete the user, log in and list all projects, exactly like you've already done
> 
>     5. in the for loop on line 68, check if the `p_id` is in the list of `public_id`s you got from step 3
> 
> 
> This way we cater for that the user may not exist, that the email may change and that we may add more projects with the creator `unituser2` in the future. So then we get good error messages and also we don't need to alter the tests if we change the user email or add more projects with the creator `unituser2`.
> 
> Let me know if you want more details etc.

Done, I am following the smae logic as in _test_user_delete_ in regards with the email / userid issue. Therefore, I have adapted the code to depend only on the specified email

**Review by i-oden — CHANGES_REQUESTED** [review]
Nice! 

Just a couple of small suggestions regarding the `__dict__` parts, they don't need to be used and you can just use `.<column>` instead

**Review by i-oden — APPROVED** [review]
Looks good! 
Feel free to merge when you're ready

**Pull request merged**
