### PR TITLE
The frontend is back and there's a no-config dev setup 

### PR DESCRIPTION
**Pull request by inaod568**
- [x] Tests passing
- [x] Black formatting
- [ - ] Migrations for any changes to the database schema
- [ - ] Rebase/merge the `dev` branch
- [ - ] Note in the CHANGELOG

### CODE REVIEW

**Review by talavis — CHANGES_REQUESTED** [review]
The backend image does not contain a built frontend. Must make sure it works before merging to master.

(see https://dds-dev.dckube.scilifelab.se/)

**Comment by inaod568** [comment]
@talavis I don't know what to do about this. The dev version looks completely different than this (the link) for me.

**Comment by talavis** [comment]
> @talavis I don't know what to do about this. The dev version looks completely different than this (the link) for me.

https://github.com/ScilifelabDataCentre/dds_web/pull/1011

**Comment by inaod568** [comment]
@talavis Looks correct in https://dds-dev.dckube.scilifelab.se/ now and the tests are passing.

**Review by talavis — APPROVED** [review]

**Pull request merged**
