### PR TITLE
Flask command Init-dev-db

### PR DESCRIPTION
**Pull request by alneberg**
An additional flask command `init-dev-db` to decide when to create the tables and put the development data in the database. In the end this turned out to be more of an exercise to understand the flask internals a tiny bit better. It's actually not needed anymore since it's controlled by the `USE_LOCAL_DB` and the integrity error is already fixed with the `check_if_fill` method in `init_db`. 

I guess one can argue that this PR represents a slightly cleaner approach since the data is there is only one attempt to add the development data in the initial start of the container, while the solution in place right now will be triggered (but not followed through) for every restart of flask (read every code change).

### CODE REVIEW

**Comment by inaod568** [comment]
I see that the `black` check is failing - do you have black installed locally?

**Review by inaod568 — APPROVED** [review]
Tried it out and it works 👍🏻 A bit concerned that it doesn't seem to notice if something is obviously wrong in the code though but I don't think that's an issue created in this PR

**Comment by inaod568** [comment]
Just make sure to merge dev first as well

**Comment by alneberg** [comment]
Great!

> A bit concerned that it doesn't seem to notice if something is obviously wrong in the code though but I don't think that's an issue created in this PR

Not sure what you mean with this

**Comment by inaod568** [comment]
> Great!
> 
> > A bit concerned that it doesn't seem to notice if something is obviously wrong in the code though but I don't think that's an issue created in this PR
> 
> Not sure what you mean with this

If I write something in the code e.g. just some jibberish then it should give errors/exceptions etc but it doesn't.

**Pull request merged**
