### PR TITLE
DDS-2019 update Trivy action

### PR DESCRIPTION
**Pull request by aishling-scilifelab**
## 1. Description / Summary

Update some aspects of the Trivy scan GitHub Actions, namely removing the invalid `branches` keyword and updating the versions of both github/codeql-action/upload-sarif (to v3 from v2) and aquasecurity/trivy-action (to 0.24.0 from 0.7.1). 

## 2. Jira task / GitHub issue

_Link to the github issue or add the Jira task ID here._

## 3. Type of change

What _type of change(s)_ does the PR contain?

**Check the relevant boxes below. For an explanation of the different sections, enter edit mode of this PR description template.**

- [ ] New feature
  - [ ] Breaking: _Why / How? Add info here._ 
  - [ ] Non-breaking 
- [ ] Database change: _Remember the to include a new migration version, **or** explain here why it's not needed._ 
- [ ] Bug fix 
- [ ] Security Alert fix 
  - [ ] Package update 
    - [ ] Major version update 
- [ ] Documentation 
- [x] Workflow 
- [ ] Tests **only** 

## 4. Additional information

- [x] [Sprintlog](../SPRINTLOG.md) 
- [ ] Blocking PRs 
  - [ ] Merged 
- [ ] PR to `master` branch: \_If checked, read [the release instructions](../doc/procedures/new_release.md) 
  - [ ] I have followed steps 1-8. 

## 5. Actions / Scans

_Check the boxes when the specified checks have passed._

**For information on what the different checks do and how to fix it if they're failing, enter edit mode of this description or go to the [PR template](../.github/pull_request_template.md).**

- [ ] **Black**

- [ ] **Prettier**

- [ ] **Yamllint**

- [ ] **Tests**

- [ ] **CodeQL**

- [ ] **Trivy**

- [ ] **Snyk**

### CODE REVIEW

**Comment by rv0lt** [comment]
Pretty straightforward. Just two small comments:

1. Have we checked that this update in the action version do not break anything?
2. Also, could you fill a small description in the action?

**Comment by aishling-scilifelab** [comment]
> Pretty straightforward. Just two small comments:
> 
> 1. Have we checked that this update in the action version do not break anything?
> 2. Also, could you fill a small description in the action?

On 1) I have checked it in that the Trivy scan still works here but is there anything else you think I should look for?
On 2), do you mean in the commit message, in the SPRINTLOG or somewhere else?

**Comment by rv0lt** [comment]
> On 1) I have checked it in that the Trivy scan still works here but is there anything else you think I should look for?

1. Nothing specially, when I update some dependency, I mainly look at the changelogs to see if there is some weird change.

2. In the PR I mean, there is this automatically template with a **Description / Summary** section on top.

**Comment by aishling-scilifelab** [comment]
> > On 1) I have checked it in that the Trivy scan still works here but is there anything else you think I should look for?
> 
> 1. Nothing specially, when I update some dependency, I mainly look at the changelogs to see if there is some weird change.
> 2. In the PR I mean, there is this automatically template with a **Description / Summary** section on top.

Updated the description. 

Re: the changelogs for the action version updates, looked at the upload-sarif (which was simple because we're just going from v2 to v3). On the trivy-action though, it's much harder to go through the changelog because we were so behind - 0.7.1 was from August 2022. Had a quick look but still mostly relying on just the Trivy scan on the PR running as normal

**Review by rv0lt — APPROVED** [review]

**Pull request merged**
