### PR TITLE
Issue1007 input validation

### PR DESCRIPTION
**Pull request by MatthiasZepper**
- [x] Tests passing
- [x] Black formatting
- [ - ] Migrations for any changes to the database schema
- [x] Rebase/merge the `dev` branch
- [x] Note in the CHANGELOG

### CODE REVIEW

**Review by talavis — COMMENTED** [review]
Maybe it makes even more sense to also have it for the name field for users (in the web form as well)?

**Review by inaod568 — APPROVED** [review]
Looks great! And no I don't think we need to do anything in the CLI. So this is good! 

_If_ there are any complaints in the future that we don't allow certain characters we can _maybe_ change that then.

**Comment by inaod568** [comment]
> Maybe it makes even more sense to also have it for the name field for users (in the web form as well)?

Yeah we probably need to add this in more places but there are quite a few schemas and forms, so I think it's good to keep the PRs as small as possible. So this is fine for this PR 👍🏻

**Comment by inaod568** [comment]
@MatthiasZepper @talavis https://github.com/ScilifelabDataCentre/dds_web/issues/1022

**Pull request merged**
